# Generated by Django 5.2.6 on 2025-10-22 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_columns', to='workspace.workspace')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='status_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='workspace.statuscolumn'),
        ),
    ]
